version: 2.1
commands:
  print_pipeline_id:
    description: " prints the Circle CI Workflow ID from its environment variable"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID
jobs:
  print-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: echo Hello
  print-world:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: echo "EGYFWD World"
  save-hello-world-output:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: echo "Hello EGYFWD WORLD" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt          
  print-output-file:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          command: cat ~/output.txt
      - print_pipeline_id
workflows:
  Print-helloEGYWorld-workflow:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
      - save-hello-world-output
      - print-output-file:
          requires:
            - save-hello-world-output
