version: 2.1
jobs:
  print-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: echo Hello
  print-world:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: echo "EGYFWD World"
  save-hello-world-output:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - output
      - run:
          command: echo "Hello EGYFWD WORLD" > output.txt
  print-output-file:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attache_workspace:
          at: /tmp/workspace/output
      - run:
          command: cat output.txt
workflows:
  Print-helloEGYWorld-workflow:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
      - save-hello-world-output:
          requires:
            - print-world
      - save-hello-world-output
      - print-output-file:
          requires:
            - save-hello-world-output
